/**
 * Canvas Vows is a real vendor catalog, imported via
 * scripts/import-partner.mjs from _canvas-vows-feed.csv on
 * 2026-07-29. 204 products across
 * 1 categories.
 *
 * Follows the same lightweight per-partner model as every other partner
 * data file (see lib/brooklyn-delhi-data.ts): one real vendor, one real
 * price (with a real originalPrice only when the source feed's own price
 * fields showed an actual markdown — never fabricated), and one real
 * outbound affiliate/purchase link per product.
 *
 * Images: resized to fit within 1600x1600 and converted to WebP by the
 * import script, saved to public/images/canvas-vows/.
 */

export type CanvasVowsProductCategory =
  | "Uncategorized";

export type CanvasVowsProduct = {
  slug: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  deepLink: string;
  image: string;
  images: string[];
  category: CanvasVowsProductCategory;
};

export const CANVAS_VOWS_CATEGORIES: CanvasVowsProductCategory[] = [
  "Uncategorized",
];

export const CANVAS_VOWS_PRODUCTS: CanvasVowsProduct[
] = [
  {
    slug: "photo-word-art-canvas-a-personalized-word-art-canvas",
    name: "Photo Word Art Canvas - A Personalized Word Art Canvas",
    description: "Photo Word Art Canvas Special moments may only last a moment, but when you commemorate them with a piece of canvas word art from Canvas Vows, those memories can stay with you forever. By combining a photo and words on canvas from one of those cherished moments, Canvas Vows can create a stunning piece of wall art — ensuring that moment stays as fresh in your mind as the day it happened. A personalized word art canvas from Canvas Vows makes a thoughtful gift as well as a beautiful addition to your home. No matter what special moment from your life that you want to remember forever, Canvas Vows can help you create something that will make that moment last. A photo word art canvas from Canvas Vows can do more than help you remember a specific moment in your life or your loved ones’ lives. By combining a photo with word art, Canvas Vows can help recall the specific emotions and feelings of that special day. A wedding photo merged with the text of your wedding vows can make a thoughtful and unique anniversary gift for your spouse or another couple in your life. Recall your child’s birth with a baby photo featuring a special quote. Whatever the occasion, a customized piece of wall art from Canvas Vows can transform it into the perfect gift. Canvas Vows uses only the highest-quality materials — including water-based, solvent-free inks. Plus, all the hardware you need to mount your new word art canvas in your home is included. Just choose the size canvas you want. Then, provide us with the photo and whatever text you want included on your customized word art canvas. Canvas Vows will design customized canvases that will make the treasured moments in your life last well beyond your special day.",
    price: 100,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317417&a=3002879&m=90193",
    image: "/images/canvas-vows/photo-word-art-canvas-a-personalized-word-art-canvas.webp",
    images: ["/images/canvas-vows/photo-word-art-canvas-a-personalized-word-art-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "1st-anniversary-gift-a-personalized-word-art-canvas",
    name: "1st Anniversary Gift - A Personalized Word Art Canvas",
    description: "A custom canvas perfect for your 1st anniversary. Instructions Step 1: Choose your canvas size from the drop down menu and the quantity you would like to order Step 2: Place the order by pressing “Add To Cart” and check out by going to your cart *Once your order is placed you will receive a Thank You email* Step 3: Please provide the customization details for your order. You can reply to the thank you email or you email us at support@canvasvows.com with the details. Once we receive your order along with the picture and the words for your design we will begin working on your design right away! Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using one of your pictures with your vows, poem, lyrics or other words. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 100,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317426&a=3002879&m=90193",
    // Source image is dead upstream (feed URL 404s at the merchant CDN,
    // verified 2026-08-19 with passing controls — findings §22). Placeholder
    // beats the broken 404 image these pages served since import.
    image: "/images/_placeholders/image-pending.png",
    images: ["/images/_placeholders/image-pending.png"],
    category: "Uncategorized",
  },
  {
    slug: "2nd-anniversary-gift-a-personalized-word-art-canvas",
    name: "2nd Anniversary Gift - A Personalized Word Art Canvas",
    description: "A custom canvas perfect for your 2nd anniversary. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may attach the picture you would like to use for your design and send it to Support@CanvasVows.com. Please also provide the exact words you would like to use in the design. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using one of your pictures with your vows, poem, lyrics or other words. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 100,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317434&a=3002879&m=90193",
    image: "/images/canvas-vows/2nd-anniversary-gift-a-personalized-word-art-canvas.webp",
    images: ["/images/canvas-vows/2nd-anniversary-gift-a-personalized-word-art-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "sound-wave-canvas-a-personalized-design-using-your-voice-on-canvas",
    name: "Sound Wave Canvas - A Personalized Design Using Your Voice On Canvas",
    description: "Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may attach the sounds file you would like to use for your design and send it to Support@CanvasVows.com. Please also provide the exact words (if any) you would like written on the design underneath the sound wave. Alternative option: If you do not want to make your own recording you may request that we use a sound wave we already have on file. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A sound wave design. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 49.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317442&a=3002879&m=90193",
    image: "/images/canvas-vows/sound-wave-canvas-a-personalized-design-using-your-voice-on-canvas.webp",
    images: ["/images/canvas-vows/sound-wave-canvas-a-personalized-design-using-your-voice-on-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "big-family-name-sign-a-personalized-family-canvas",
    name: "Big Family Name Sign - A Personalized Family Canvas",
    description: "Big Family Name Sign Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317452&a=3002879&m=90193",
    image: "/images/canvas-vows/big-family-name-sign-a-personalized-family-canvas.webp",
    images: ["/images/canvas-vows/big-family-name-sign-a-personalized-family-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "it-was-always-you-canvas-artwork",
    name: "It Was Always You Canvas Artwork",
    description: "It Was Always You Canvas Artwork Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 100,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317460&a=3002879&m=90193",
    image: "/images/canvas-vows/it-was-always-you-canvas-artwork.webp",
    images: ["/images/canvas-vows/it-was-always-you-canvas-artwork.webp"],
    category: "Uncategorized",
  },
  {
    slug: "eat-drink-and-be-merry-home-decor-canvases",
    name: "Eat Drink And Be Merry Home Decor Canvases",
    description: "Eat Drink And Be Merry Home Decor Canvases Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 135,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317464&a=3002879&m=90193",
    image: "/images/canvas-vows/eat-drink-and-be-merry-home-decor-canvases.webp",
    images: ["/images/canvas-vows/eat-drink-and-be-merry-home-decor-canvases.webp"],
    category: "Uncategorized",
  },
  {
    slug: "first-dance-lyrics-on-canvas-a-custom-made-canvas-with-your-wedding-song",
    name: "First Dance Lyrics On Canvas - A Custom Made Canvas With Your Wedding Song",
    description: "First Dance Lyrics On Canvas Capture the memory of your first dance as a married couple with custom first dance lyrics on canvas. Using the sheet music from your first dance, Canvas Vows will create a stunning piece of art that is ready to hang and display in your home. Wherever you display a first dance lyrics print, you will create a one-of-a-kind focal point in your home that will remind you of that special day. Create a Piece of Art for Any Significant Song While putting your first dance lyrics on canvas is a way to commemorate that memorable dance at your wedding, Canvas Vows can make a beautiful work of art for any piece of sheet music you love. Whether you're celebrating your wedding dance, your special song or a piece of music that has significance to you for another reason, simply send us the sheet music and lyrics, and we will create a personalized piece of art for your home. Add Meaning to Your Home's Decor Anyone can hang a picture of music or song lyrics in his or her home. Only with custom wedding lyrics on canvas can you make that decor personalized. With the help of Canvas Vows, your home's decor becomes valuable and sentimental, special to your home and your family's story. What’s more, because only the highest-quality materials and water-based, solvent-free inks are used, your custom canvas will display beautifully for a lifetime. Are you ready? Here's how you can order your wedding song lyrics on canvas. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what song you would like to use by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using sheet music from any song you choose. (please note, we are only able to make designs for songs that have available sheet music) 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 115,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317468&a=3002879&m=90193",
    image: "/images/canvas-vows/first-dance-lyrics-on-canvas-a-custom-made-canvas-with-your-wedding-song.webp",
    images: ["/images/canvas-vows/first-dance-lyrics-on-canvas-a-custom-made-canvas-with-your-wedding-song.webp"],
    category: "Uncategorized",
  },
  {
    slug: "big-home-canvas-a-beautiful-home-decor-canvas",
    name: "Big Home Canvas - A Beautiful Home Decor Canvas",
    description: "Big Home Canvas Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317476&a=3002879&m=90193",
    image: "/images/canvas-vows/big-home-canvas-a-beautiful-home-decor-canvas.webp",
    images: ["/images/canvas-vows/big-home-canvas-a-beautiful-home-decor-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "i-love-you-more-canvas-wall-art",
    name: "I Love You More Canvas Wall Art",
    description: "I love you more canvas Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 100,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317484&a=3002879&m=90193",
    image: "/images/canvas-vows/i-love-you-more-canvas-wall-art.webp",
    images: ["/images/canvas-vows/i-love-you-more-canvas-wall-art.webp"],
    category: "Uncategorized",
  },
  {
    slug: "coffee-home-decor-canvas",
    name: "Coffee Home Decor Canvas",
    description: "Coffee canvas Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317488&a=3002879&m=90193",
    image: "/images/canvas-vows/coffee-home-decor-canvas.webp",
    images: ["/images/canvas-vows/coffee-home-decor-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "family-home-decor-canvas",
    name: "Family Home Decor Canvas",
    description: "Family canvas Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317496&a=3002879&m=90193",
    image: "/images/canvas-vows/family-home-decor-canvas.webp",
    images: ["/images/canvas-vows/family-home-decor-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "his-and-her-vows-on-canvas-personalized-wall-art",
    name: "His And Her Vows On Canvas - Personalized Wall Art",
    description: "His and hers canvas. A personalized canvas using your vows, lyrics, or poem Style Choose from two different styles. You can see the two styles in the example pictures. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what words you would like to use for your design by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using the words of your choice. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 129,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317504&a=3002879&m=90193",
    image: "/images/canvas-vows/his-and-her-vows-on-canvas-personalized-wall-art.webp",
    images: ["/images/canvas-vows/his-and-her-vows-on-canvas-personalized-wall-art.webp"],
    category: "Uncategorized",
  },
  {
    slug: "mr-and-mrs-vows-on-canvas-personalized-wall-art",
    name: "Mr And Mrs Vows On Canvas - Personalized Wall Art",
    description: "Mr and Mrs canvas. A personalized canvas using your vows, lyrics, or poem Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what words you would like to use for your design by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using the words of your choice. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 129,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317507&a=3002879&m=90193",
    image: "/images/canvas-vows/mr-and-mrs-vows-on-canvas-personalized-wall-art.webp",
    images: ["/images/canvas-vows/mr-and-mrs-vows-on-canvas-personalized-wall-art.webp"],
    category: "Uncategorized",
  },
  {
    slug: "first-wedding-anniversary-gift-your-wedding-vows-on-canvas",
    name: "First Wedding Anniversary Gift - Your Wedding Vows On Canvas",
    description: "A personalized anniversary canvas using your wedding vows, lyrics or poem. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may attach the picture you would like to use for your design and send it to Support@CanvasVows.com. Please also provide the exact words you would like to use in the design. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using one of your pictures with your vows, poem, lyrics or other words. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 100,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317510&a=3002879&m=90193",
    image: "/images/canvas-vows/first-wedding-anniversary-gift-your-wedding-vows-on-canvas.webp",
    images: ["/images/canvas-vows/first-wedding-anniversary-gift-your-wedding-vows-on-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "first-dance-song-canvas-a-design-covering-the-entire-canvas-with-lyrics",
    name: "First Dance Song Canvas - A Design Covering The Entire Canvas With Lyrics",
    description: "First Dance Song Canvas Create a custom canvas using your first dance song or any song that is meaningful to you. The lyrics from your song cover the entire width and height of the canvas. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what song you would like to use by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using any words you choose. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 115,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317518&a=3002879&m=90193",
    image: "/images/canvas-vows/first-dance-song-canvas-a-design-covering-the-entire-canvas-with-lyrics.webp",
    images: ["/images/canvas-vows/first-dance-song-canvas-a-design-covering-the-entire-canvas-with-lyrics.webp"],
    category: "Uncategorized",
  },
  {
    slug: "relax-soak-and-unwind-wall-art",
    name: "Relax Soak And Unwind Wall Art",
    description: "Relax Soak And Unwind Home Decor Details Dress up your bathroom with relax, soak, unwind wall art! Displaying a message of comfort and luxury, this charming home decor helps turn any bathroom into a spa-like space. Hang this three-piece wall art set above the soaking tub or on any open wall to add a personalized touch and style to your bathroom’s design. Available in both print and canvas styles, this artwork comes in a variety of sizes, so you can go as small or large as fits your bathroom. Plus, each canvas can be made in a custom color of your choice, so it fits your space. Just write your color request in the order notes, and we’ll send you a preview before it’s printed and shipped. Hanging a Relax, Soak, Unwind Canvas Set in the Bathroom Everybody understands the appeal of having a spa-like retreat in their bathroom at home. From a large soaking tub to a walk-in shower, the elements of your bathroom all combine to create a sense of tranquil ambiance. Yet one other key element in luxury bathrooms is the decorating. Through carefully chosen artwork such as our relax, soak, unwind canvas set, you can communicate the overall ambiance you desire. Instructions for Ordering Step 1: Choose your size from the menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? When you order relax, soak, unwind wall art, you receive a three-piece canvas set printed onto either professional print paper or canvas at the chosen size. Benefits of Our Canvas Materials at Canvas Vows Top quality : Only high-end materials and strict quality controls are used in each and every print and canvas we provide. Safe materials : Our canvases are safe for the whole family as only HP Latex inks are used. These inks are water-based, solvent-free and odorless. Ready to hang : All of our canvases come with the needed hardware in order to be hung anywhere in the home. Canvas thickness: Each piece comes with a standard .75″ wood frame (1.5″ is an available upgrade).",
    price: 45,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317526&a=3002879&m=90193",
    image: "/images/canvas-vows/relax-soak-and-unwind-wall-art.webp",
    images: ["/images/canvas-vows/relax-soak-and-unwind-wall-art.webp"],
    category: "Uncategorized",
  },
  {
    slug: "american-flag-canvas",
    name: "American Flag Canvas",
    description: "A rustic looking American flag printed on canvas. There are multiple sizes available. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 59,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317537&a=3002879&m=90193",
    image: "/images/canvas-vows/american-flag-canvas.webp",
    images: ["/images/canvas-vows/american-flag-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "thin-blue-line-flag-personalized-canvas",
    name: "Thin Blue Line Flag - Personalized Canvas",
    description: "Thin Blue Line Flag Canvas Details Honor the ones who protect and preserve our nation with a personalized piece of thin blue line wall art. Customized with the name of an officer and/or badge number that is important to you, your thin blue line canvas is a powerful way to memorialize a loved one’s work and sacrifice. Alternatively, a simple thin blue line canvas without personalization can communicate your overall support of the police force. Either way, with a thin blue line flag canvas, you honor someone who has sacrificed each day to serve and protect the community. Canvas Vows offers this meaningful artwork in multiple sizes, so you can pick the piece that fits your home best. About the Thin Blue Line Set against a black background, the thin blue line is a recognized symbol that represents law enforcement — a force of good and order standing against anarchy and crime. When displayed in your home, it communicates solidarity with the police force and/or can commemorate someone who died in the line of duty. Whether you’re interested in a customized canvas or standard thin blue line wall art, Canvas Vows is your resource for the best quality and value. When you’re ready to place an order for a thin blue line flag canvas, follow the instructions below: Instructions for Ordering Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? When you order thin blue line wall art from Canvas Vows, you receive a canvas in your choice of size, printed onto a quality canvas. Benefits of Our Canvas Materials Quality manufacturing : Only high-end materials and strict quality controls are used in each and every canvas print. Safe inks : Our canvases are safe for the whole family, as only HP Latex inks are used. These inks are water-based, solvent-free and odorless. Ready to hang : All canvases come with the needed hardware in order to hang them anywhere in the home. Canvas thickness : Standard .75″ wood frame (1.5″ is an available upgrade).",
    price: 59,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317539&a=3002879&m=90193",
    image: "/images/canvas-vows/thin-blue-line-flag-personalized-canvas.webp",
    images: ["/images/canvas-vows/thin-blue-line-flag-personalized-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "thin-red-line-a-personalized-gift-for-firefighter",
    name: "Thin Red Line - A Personalized Gift For Firefighter",
    description: "A thin red line flag canvas. To honor those who sacrifice each day to ensure our safety. There are multiple sizes available. Makes a great gift for a firefighter. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose whether or not you would like it personalized using a name and badge number (optional). You can also request something else written instead. Step 3. Choose how many you would like to order. Step 4: Place the order by pressing “Add To Cart” Step 5: Check out by going to your cart Step 6: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 59,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317543&a=3002879&m=90193",
    image: "/images/canvas-vows/thin-red-line-a-personalized-gift-for-firefighter.webp",
    images: ["/images/canvas-vows/thin-red-line-a-personalized-gift-for-firefighter.webp"],
    category: "Uncategorized",
  },
  {
    slug: "lyrics-in-a-heart-canvas-personalized-canvas",
    name: "Lyrics In A Heart Canvas - Personalized Canvas",
    description: "First Dance Song Canvas Create a custom canvas using your first dance song or any song that is meaningful to you. The lyrics from your song will be in a heart shape. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what song you would like to use by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using any words you choose. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 115,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317547&a=3002879&m=90193",
    image: "/images/canvas-vows/lyrics-in-a-heart-canvas-personalized-canvas.webp",
    images: ["/images/canvas-vows/lyrics-in-a-heart-canvas-personalized-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "baby-s-heartbeat-soundwave-canvas",
    name: "Baby's Heartbeat Soundwave Canvas",
    description: "A sound wave canvas Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may attach the sounds file you would like to use for your design and send it to Support@CanvasVows.com. Please also provide the exact words (if any) you would like written on the design underneath the sound wave. Alternative option: If you do not want to make your own recording you may request that we use a sound wave we already have on file. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A sound wave design. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 100,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317555&a=3002879&m=90193",
    image: "/images/canvas-vows/baby-s-heartbeat-soundwave-canvas.webp",
    images: ["/images/canvas-vows/baby-s-heartbeat-soundwave-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "love-arrow-canvas",
    name: "Love Arrow Canvas",
    description: "A personalized love arrow canvas. Customize with your names and a special date. It can also be made without names and a date if preferred. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Place the custom details in the notes section during checkout. Step 6: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317563&a=3002879&m=90193",
    image: "/images/canvas-vows/love-arrow-canvas.webp",
    images: ["/images/canvas-vows/love-arrow-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "last-name-canvas-a-personalized-family-sign",
    name: "Last Name Canvas - A Personalized Family Sign",
    description: "A personalized canvas using your family's last name and established date. This design also has the quote \"home sweet home\". Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317571&a=3002879&m=90193",
    image: "/images/canvas-vows/last-name-canvas-a-personalized-family-sign.webp",
    images: ["/images/canvas-vows/last-name-canvas-a-personalized-family-sign.webp"],
    category: "Uncategorized",
  },
  {
    slug: "established-sign-canvas",
    name: "Established Sign Canvas",
    description: "A personalized established sign canvas. Use your last name Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317579&a=3002879&m=90193",
    image: "/images/canvas-vows/established-sign-canvas.webp",
    images: ["/images/canvas-vows/established-sign-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "custom-ultrasound-canvas",
    name: "Custom Ultrasound Canvas",
    description: "A sound wave canvas Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may attach the sounds file you would like to use for your design and send it to Support@CanvasVows.com. Please also provide the exact words (if any) you would like written on the design underneath the sound wave. Alternative option: If you do not want to make your own recording you may request that we use a sound wave we already have on file. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A sound wave design. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 45,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317587&a=3002879&m=90193",
    image: "/images/canvas-vows/custom-ultrasound-canvas.webp",
    images: ["/images/canvas-vows/custom-ultrasound-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "coffee-sign-farmhouse-style",
    name: "Coffee Sign - Farmhouse Style",
    description: "Coffee Sign Canvas Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317595&a=3002879&m=90193",
    image: "/images/canvas-vows/coffee-sign-farmhouse-style.webp",
    images: ["/images/canvas-vows/coffee-sign-farmhouse-style.webp"],
    category: "Uncategorized",
  },
  {
    slug: "framed-song-lyrics-and-sheet-music-custom-canvas",
    name: "Framed Song Lyrics And Sheet Music Custom Canvas",
    description: "A personalized sheet music canvas. It includes 2 sheet music stanzas, the title of the song and the lyrics of the song. This is personalized to your liking (color, size, design). This can make a great anniversary gift or just a great addition to your home decor.",
    price: 115,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317603&a=3002879&m=90193",
    image: "/images/canvas-vows/framed-song-lyrics-and-sheet-music-custom-canvas.webp",
    images: ["/images/canvas-vows/framed-song-lyrics-and-sheet-music-custom-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "wedding-guest-book",
    name: "Wedding Guest Book",
    description: "Wedding Guest Book Create a beautiful guest book for your wedding. Our guest books can be designed to include as many guests as you need. Custom color - you can customize the design to be any color you would like. Instructions Step 1: Choose your size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what how many guests you will have by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A guest book design using little hearts for the guest signatures. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas Material: 15 Mil Polyester Cotton Blend Canvas Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 70,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317604&a=3002879&m=90193",
    image: "/images/canvas-vows/wedding-guest-book.webp",
    images: ["/images/canvas-vows/wedding-guest-book.webp"],
    category: "Uncategorized",
  },
  {
    slug: "wedding-guest-book-large-heart-alternative",
    name: "Wedding Guest Book - Large Heart Alternative",
    description: "Wedding Guest Book Create a beautiful guest book for your wedding. Our guest books can be designed to include as many guests as you need. Custom color - you can customize the design to be any color you would like. Instructions Step 1: Choose your size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what how many guests you will have by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A guest book design using little hearts for the guest signatures. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas Material: 15 Mil Polyester Cotton Blend Canvas Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 70,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317605&a=3002879&m=90193",
    image: "/images/canvas-vows/wedding-guest-book-large-heart-alternative.webp",
    images: ["/images/canvas-vows/wedding-guest-book-large-heart-alternative.webp"],
    category: "Uncategorized",
  },
  {
    slug: "custom-star-map",
    name: "Custom Star Map",
    description: "Create a meaningful custom star map. Use a special location using coordinates and the date of the special night. We'll use your coordinates to recreate the night sky of your special night. DETAILS Words: You can use your wedding vows, your first dance song from your wedding, another meaningful song or any other words you would like. Location: This design is made with the night sky of the exact location of your choosing. You can tell us the coordinates or give us an address and we can find out the coordinates for you. Date: Please let us know what the date is of your meaningful location. The night sky map will look exactly as the night sky did in that location on that specific night! Additional details: We can also write in additional details if you would like the date, address or other details written on the design. NOTE: Please write these details in the order notes during checkout. OPTIONS • Matte Print You can choose a matte print size. If you choose one of these sizes, your design will be printed on professional grade matte paper. It does not include a frame. There are hundreds of different frame styles, colors and sizes. We leave framing up to the professional framing stores. • Canvas Print If you choose a canvas size you will receive a fully wrapped canvas. The canvas is ready to hang straight out of the box. ---------------------------------------------------- HOW TO ORDER 1. Choose your size in the drop down menu. 2. Once your size is chosen you can place the order by clicking \"Add to cart\" 3. Message us on Etsy and let us know the details for your design. Or you can put the details in the order notes during checkout. 4. You will receive a proof of your design so you can make desired changes and approve the final design before it ships. ---------------------------------------------------- HANGING YOUR ARTWORK • Matte print will need to be framed or mounted once you receive it in order for it to hang on the wall. • Our canvases come ready to hang straight out of the box. ----------------------------------------------------- QUALITY • Our desire is for you to absolutely love your artwork. That is why we put an emphasis on craftsmanship. Our matte prints are professional grade print paper and our canvases are hand stretched onto a thick wooden frame. ----------------------------------------------------- CUSTOMER CARE AND SUPPORT • We understand the importance of having questions answered quickly and thoroughly. We do our best to have your questions answered with a 24 hour time frame. (Please note that we do not work on the weekends. If you reach out over the weekend, you will be answered first thing Monday morning) ----------------------------------------------------- PROCESSING AND SHIPPING Please see our current processing and shipping times here . Please visit some of my other work: https://www.CanvasVows.com https://www.instagram.com/canvasvows/ If you have any questions please do not hesitate to message me :)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317606&a=3002879&m=90193",
    // Source image is dead upstream (feed URL 404s at the merchant CDN,
    // verified 2026-08-19 with passing controls — findings §22). Placeholder
    // beats the broken 404 image these pages served since import.
    image: "/images/_placeholders/image-pending.png",
    images: ["/images/_placeholders/image-pending.png"],
    category: "Uncategorized",
  },
  {
    slug: "night-sky-map",
    name: "Night Sky Map",
    description: "Create a meaningful custom night sky map. Use a special location using coordinates and the date of the special night. We'll use your coordinates to recreate the night sky of your special night. DETAILS Words: You can use your wedding vows, your first dance song from your wedding, another meaningful song or any other words you would like. Location: This design is made with the night sky of the exact location of your choosing. You can tell us the coordinates or give us an address and we can find out the coordinates for you. Date: Please let us know what the date is of your meaningful location. The night sky map will look exactly as the night sky did in that location on that specific night! Additional details: We can also write in additional details if you would like the date, address or other details written on the design. NOTE: Please write these details in the order notes during checkout. OPTIONS • Matte Print You can choose a matte print size. If you choose one of these sizes, your design will be printed on professional grade matte paper. It does not include a frame. There are hundreds of different frame styles, colors and sizes. We leave framing up to the professional framing stores. • Canvas Print If you choose a canvas size you will receive a fully wrapped canvas. The canvas is ready to hang straight out of the box. ---------------------------------------------------- HOW TO ORDER 1. Choose your size in the drop down menu. 2. Once your size is chosen you can place the order by clicking \"Add to cart\" 3. Message us on Etsy and let us know the details for your design. Or you can put the details in the order notes during checkout. 4. You will receive a proof of your design so you can make desired changes and approve the final design before it ships. ---------------------------------------------------- HANGING YOUR ARTWORK • Matte print will need to be framed or mounted once you receive it in order for it to hang on the wall. • Our canvases come ready to hang straight out of the box. ----------------------------------------------------- QUALITY • Our desire is for you to absolutely love your artwork. That is why we put an emphasis on craftsmanship. Our matte prints are professional grade print paper and our canvases are hand stretched onto a thick wooden frame. ----------------------------------------------------- CUSTOMER CARE AND SUPPORT • We understand the importance of having questions answered quickly and thoroughly. We do our best to have your questions answered with a 24 hour time frame. (Please note that we do not work on the weekends. If you reach out over the weekend, you will be answered first thing Monday morning) ----------------------------------------------------- PROCESSING AND SHIPPING Please see our current processing and shipping times here . Please visit some of my other work: https://www.CanvasVows.com https://www.instagram.com/canvasvows/ If you have any questions please do not hesitate to message me :)",
    price: 65,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317607&a=3002879&m=90193",
    image: "/images/canvas-vows/night-sky-map.webp",
    images: ["/images/canvas-vows/night-sky-map.webp"],
    category: "Uncategorized",
  },
  {
    slug: "song-sound-wave-art",
    name: "Song Sound Wave Art",
    description: "Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. In the email you can tell us which song you would like to use for your order. Please also provide the exact words (if any) you would like written on the design underneath the sound wave. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A sound wave design. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 49.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317608&a=3002879&m=90193",
    image: "/images/canvas-vows/song-sound-wave-art.webp",
    images: ["/images/canvas-vows/song-sound-wave-art.webp"],
    category: "Uncategorized",
  },
  {
    slug: "his-and-hers-panoramic-canvas",
    name: "His And Hers Panoramic Canvas",
    description: "A beautiful wide format panoramic his and hers canvas. This design fits perfectly over any sized bed or couch. Designed In House We are a team of professional graphic designers who put love and care into every design. ------------------------------------- Printed In House We print our designs/orders in house. We use high end large format printers to print onto canvas material. We then hand stretch the print to make a completed the canvas. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what words you would like to use for your design by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using the words of your choice. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 129,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317609&a=3002879&m=90193",
    image: "/images/canvas-vows/his-and-hers-panoramic-canvas.webp",
    images: ["/images/canvas-vows/his-and-hers-panoramic-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "his-and-hers-wall-art",
    name: "His And Hers Wall Art",
    description: "A unique take on the His And Hers design. This version uses your favorite picture in the design. It can a wedding picture or any other picture you like. Designed In House We are a team of professional graphic designers who put love and care into every design. ------------------------------------- Printed In House We print our designs/orders in house. We use high end large format printers to print onto canvas material. We then hand stretch the print to make a completed the canvas. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what words you would like to use for your design by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using the words of your choice. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 90,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317610&a=3002879&m=90193",
    image: "/images/canvas-vows/his-and-hers-wall-art.webp",
    images: ["/images/canvas-vows/his-and-hers-wall-art.webp"],
    category: "Uncategorized",
  },
  {
    slug: "sheet-music-wall-art",
    name: "Sheet Music Wall Art",
    description: "Sheet Music Wall Art Create your personalized sheet music wall art using your favorite song. We take your chosen song and use the sheet music to create beautiful canvas. Our sheet music canvases make a great gift option for anniversary gifts, birthday gifts or additions to your home decor. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what song you would like to use by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using sheet music from any song you choose. (please note, we are only able to make designs for songs that have available sheet music) 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 115,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317612&a=3002879&m=90193",
    image: "/images/canvas-vows/sheet-music-wall-art.webp",
    images: ["/images/canvas-vows/sheet-music-wall-art.webp"],
    category: "Uncategorized",
  },
  {
    slug: "triptych-song-lyrics-canvas",
    name: "Triptych Song Lyrics Canvas",
    description: "Add this is 3 panel (triptych) canvas design to your home decor. It is a personalized 3 piece print using any song, words, or vows you would like to use. It can also incorporate your names and important dates. Original Design - This is an original design of Canvas Vows ------------------------------------- Material Options • Paper Print - This option is for a paper print (this means it is not a canvas). It comes rolled and does not include a frame. This option is best if you would like to display your design in a frame rather than as a canvas. • Canvas - This option is a fully gallery wrapped canvas that comes ready to hang straight out of the box. What is a gallery wrapped canvas? Read more here. ------------------------------------- Size Options The size options show \"Print Paper\" and \"Canvas\". The difference between those two are explained above. The size for each of the options gives you the size of 1 of 3 prints that come in your order. For example, the first option is \"16x20 Paper Print\". This option is telling you the size of just one of the 3 prints you will receive. This means you will receive 3 paper prints that are 16x20\" each. The total size of all 3 would be 48x20\". Please let us know if you have any questions about the sizes . ------------------------------------- Designed In House We are a team of professional graphic designers who put love and care into every design. ------------------------------------- Printed In House We print our designs/orders in house. We use high end large format printers to print onto canvas material. We then hand stretch the print to make a completed the canvas. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what words you would like to use for your design by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using the words of your choice. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 60,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317613&a=3002879&m=90193",
    image: "/images/canvas-vows/triptych-song-lyrics-canvas.webp",
    images: ["/images/canvas-vows/triptych-song-lyrics-canvas.webp"],
    category: "Uncategorized",
  },
  {
    slug: "lyric-canvas-art",
    name: "Lyric Canvas Art",
    description: "Lyric Canvas Art Create a custom canvas using your using your favorite song. This design puts the lyrics across the entire canvas and the song title bold in the middle. It also has a nice light gray background texture. This design makes a great anniversary gift or simply a beautiful work of art for your home decor. Personalization Options • Song - choose any song you would like to use. If you would like, we can also use your wedding vows instead or other written words. • Color - the font and background color can be changed to any color you would like. • Background - the background has a nice gray flower texture that is very light. It can be changed to any color you would like or the texture can be removed and you do any flat color for your background. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know what song you would like to use by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A design using any words you choose. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 115,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317616&a=3002879&m=90193",
    image: "/images/canvas-vows/lyric-canvas-art.webp",
    images: ["/images/canvas-vows/lyric-canvas-art.webp"],
    category: "Uncategorized",
  },
  {
    slug: "last-name-sign-rustic-brown",
    name: "Last Name Sign - Rustic Brown",
    description: "Add a cozy family name canvas to your home. This is personalized with your family's last name and kids names. We can personalize this canvas to your liking. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317617&a=3002879&m=90193",
    image: "/images/canvas-vows/last-name-sign-rustic-brown.webp",
    images: ["/images/canvas-vows/last-name-sign-rustic-brown.webp"],
    category: "Uncategorized",
  },
  {
    slug: "family-name-sign-rustic-white",
    name: "Family Name Sign - Rustic White",
    description: "A classic addition to any family home. This rustic white wooden textured canvas is personalized with your family's last name and kids names. We can personalize this canvas to your liking. Instructions Step 1: Choose your canvas size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) This canvas design printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas thickness: Standard .75″ wood frame (1.5″ is an available upgrade)",
    price: 75,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317618&a=3002879&m=90193",
    image: "/images/canvas-vows/family-name-sign-rustic-white.webp",
    images: ["/images/canvas-vows/family-name-sign-rustic-white.webp"],
    category: "Uncategorized",
  },
  {
    slug: "wedding-guest-book-alternative-watercolor-states",
    name: "Wedding Guest Book Alternative - Watercolor States",
    description: "Wedding Guest Book Alternative This is a unique wedding guest book. Traditional guest books are usually forgotten after the wedding. Since they are books they get put on the shelf and never looked out. Our alternative guest books gets signatures from your guests straight onto a ready to hang canvas. This creates the ultimate wedding keepsake that is ready to be displayed on your wall. We can use any states or countries you would like and any colors you would like as well. Instructions Step 1: Choose your size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know the custom details by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A custom designed guest book. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas Material: 15 Mil Polyester Cotton Blend Canvas Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 80,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317619&a=3002879&m=90193",
    image: "/images/canvas-vows/wedding-guest-book-alternative-watercolor-states.webp",
    images: ["/images/canvas-vows/wedding-guest-book-alternative-watercolor-states.webp"],
    category: "Uncategorized",
  },
  {
    slug: "wedding-guest-book-where-we-are-from",
    name: "Wedding Guest Book Where We Are From",
    description: "Wedding Guest Book - Where We Are From This wedding guest book idea uses the countries or states that you are from. This is a beautiful twist on the traditional guest books that are used for weddings. Our guest books can be hung up as wall art after the wedding instead of put on a shelf and hidden like most guest books. We can use any states or countries and we can personalize the colors to your liking. Instructions Step 1: Choose your size from the drop down menu. Step 2: Choose how many you would like to order. Step 3: Place the order by pressing “Add To Cart” Step 4: Check out by going to your cart Step 5: Once the order is placed, you will receive a thank you email from Support@CanvasVows.com. You may let us know the custom details by sending an email to Support@CanvasVows.com or by replying to your thank you email. Processing & Shipping Time Please see our current processing and shipping times here . What is included in your purchase? 1) A custom designed guest book. 2) Your design is printed onto a canvas at the size you select. Canvas Materials Only high end materials and strict quality controls are used in each and every canvas print. Canvases are safe for the whole family as only HP Latex inks are used. These inks are water based, solvent-free and odorless. Ready to hang: All canvases come with the needed hardware in order to hang it anywhere in the home. Canvas Material: 15 Mil Polyester Cotton Blend Canvas Canvas thickness: Standard .75″ wood frame (1.5″ also available)",
    price: 80,
    deepLink: "https://www.awin1.com/pclick.php?p=41668317620&a=3002879&m=90193",
    image: "/images/canvas-vows/wedding-guest-book-where-we-are-from.webp",
    images: ["/images/canvas-vows/wedding-guest-book-where-we-are-from.webp"],
    category: "Uncategorized",
  },
];
