/**
 * King Koil is a real vendor catalog, imported via
 * scripts/import-partner.mjs from _king-koil-feed.csv on
 * 2026-07-29. 31 products across
 * 1 categories.
 *
 * Follows the same lightweight per-partner model as every other partner
 * data file (see lib/brooklyn-delhi-data.ts): one real vendor, one real
 * price (with a real originalPrice only when the source feed's own price
 * fields showed an actual markdown — never fabricated), and one real
 * outbound affiliate/purchase link per product.
 *
 * Images: resized to fit within 1600x1600 and converted to WebP by the
 * import script, saved to public/images/king-koil/.
 */

export type KingKoilProductCategory =
  | "Mattresses";

export type KingKoilProduct = {
  slug: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  deepLink: string;
  image: string;
  images: string[];
  category: KingKoilProductCategory;
};

export const KING_KOIL_CATEGORIES: KingKoilProductCategory[] = [
  "Mattresses",
];

export const KING_KOIL_PRODUCTS: KingKoilProduct[] = [
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 99.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43487196554&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-2",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 109.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43487196555&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-2.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-2.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-3",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 119.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328560&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-3.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-3.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-4",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 129.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328561&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-4.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-4.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-5",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 149.95,
    deepLink: "https://www.awin1.com/pclick.php?p=42912979431&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-5.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-5.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-6",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 179.95,
    deepLink: "https://www.awin1.com/pclick.php?p=42890768720&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-6.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-6.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-7",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 79.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328562&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-7.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-7.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-8",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 159.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43487196557&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-8.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-8.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-9",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 139.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328563&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-9.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-9.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-10",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 129.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41333549307&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-10.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-10.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-11",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 159.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43487196558&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-11.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-11.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-with-high-speed-built-in-pump-12",
    name: "King Koil Luxury Air Mattress with High Speed Built-in Pump",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 119.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43487196559&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-12.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-with-high-speed-built-in-pump-12.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 119.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328564&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige-2",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 149.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328565&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige-2.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige-2.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige-3",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 179.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328566&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige-3.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige-3.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige-4",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 89.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43487196560&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige-4.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige-4.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige-5",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 109.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328567&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige-5.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige-5.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige-6",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 119.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41203582282&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige-6.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige-6.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige-7",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 139.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328568&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige-7.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige-7.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige-8",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 129.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41333549308&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige-8.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige-8.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige-9",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 139.95,
    deepLink: "https://www.awin1.com/pclick.php?p=42597421172&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige-9.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige-9.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-air-mattress-beige-10",
    name: "King Koil Air Mattress - Beige",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed&#39;s shape and firmness over time.. Layers - Utilizing high-quality, puncture resistant material prevents normal wear and tear that can.sink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 159.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41333549310&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-air-mattress-beige-10.webp",
    images: ["/images/king-koil/king-koil-air-mattress-beige-10.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-blue",
    name: "King Koil Luxury Air Mattress - Blue",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air-filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture-resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 109.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41333549311&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-blue.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-blue.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-blue-2",
    name: "King Koil Luxury Air Mattress - Blue",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air-filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture-resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 119.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43391891131&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-blue-2.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-blue-2.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-blue-3",
    name: "King Koil Luxury Air Mattress - Blue",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air-filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture-resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 129.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43317328569&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-blue-3.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-blue-3.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-blue-4",
    name: "King Koil Luxury Air Mattress - Blue",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air-filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture-resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 149.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41333549314&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-blue-4.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-blue-4.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-blue-5",
    name: "King Koil Luxury Air Mattress - Blue",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air-filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture-resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 159.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41333549315&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-blue-5.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-blue-5.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-blue-6",
    name: "King Koil Luxury Air Mattress - Blue",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air-filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture-resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 179.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43332184759&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-blue-6.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-blue-6.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-blue-7",
    name: "King Koil Luxury Air Mattress - Blue",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air-filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture-resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 129.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41333549317&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-blue-7.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-blue-7.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-blue-8",
    name: "King Koil Luxury Air Mattress - Blue",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air-filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture-resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 139.95,
    deepLink: "https://www.awin1.com/pclick.php?p=43324857534&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-blue-8.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-blue-8.webp"],
    category: "Mattresses",
  },
  {
    slug: "king-koil-luxury-air-mattress-blue-9",
    name: "King Koil Luxury Air Mattress - Blue",
    description: "Coil Beam - King Koil Airbeds were designed with you in mind. Enhanced Coil Technology providesthe support you and your guests need for a sound night's sleep. Air-filled coils and internal layeringnaturally support the body, keeping the spine aligned as you sleep. The state-of-the-art coils also maintain the inflatable bed's shape and firmness over time.. Layers - Utilizing high-quality, puncture-resistant material prevents normal wear and tear that cansink an average air mattress. The durable PVC combined with soft flocked top create a waterproof,extremely durable airbed, meant to withstand the test of time.. Built-In Pump - With our proprietary built-in high-speed pump, you can easily maintain and adjust the blow up beds firmness level. Featuring separate inflation and deflation valves, the built-in high speed pump will do the work for you, and get you resting faster. Fully inflate or deflate the queen size air mattress in just 90 seconds. That's twice as fast as the average competing bed! Pump specs: 120V/210W",
    price: 79.95,
    deepLink: "https://www.awin1.com/pclick.php?p=41333549319&a=3002879&m=115216",
    image: "/images/king-koil/king-koil-luxury-air-mattress-blue-9.webp",
    images: ["/images/king-koil/king-koil-luxury-air-mattress-blue-9.webp"],
    category: "Mattresses",
  },
];
